env:
  global:
    - CC_TEST_REPORTER_ID=42f23507800f7e37490680c9eb163455d5214d7f8c7140d0757e4858fa809497
language: ruby
rvm:
 - 2.1.3
 - 2.2.7
 - 2.3.6
 - 2.4.1
 - ruby-head

branches:
  only:
    - master

before_install:
  - [[ $BUNDLE_GEMFILE = *"rails_5_2"* ]] && {
      echo "Installing Cucumber-rails v1.6.0.pre...";
      gem install cucumber-rails-1.6.0.pre.gem;
    } || echo "Rails version is < 5.2. Not installing Cucumber 1.6.0.pre!"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

gemfile:
#  - gemfiles/rails_3.gemfile
#  - gemfiles/rails_4_0.gemfile
#  - gemfiles/rails_4_1.gemfile
#  - gemfiles/rails_4_2.gemfile
#  - gemfiles/rails_5_0.gemfile
#  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.1.3
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: 2.1.3
      gemfile: gemfiles/rails_4_2.gemfile
    - rvm: 2.1.3
      gemfile: gemfiles/rails_5_0.gemfile
    - rvm: 2.1.3
      gemfile: gemfiles/rails_5_1.gemfile
    - rvm: 2.1.3
      gemfile: gemfiles/rails_5_2.gemfile
    - rvm: 2.2.7
      gemfile: gemfiles/rails_3.gemfile
    - rvm: 2.3.6
      gemfile: gemfiles/rails_3.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_3.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4_1.gemfile
    - rvm: jruby
      gemfile: gemfiles/rails_3.gemfile
    - rvm: rbx-3
      gemfile: gemfiles/rails_3.gemfile
  allow_failures:
    - rvm: ruby-head