language: ruby
rvm:
 #- 2.1.3
 #- 2.2.7
 - 2.3.6
 #- 2.4.1
 #- jruby
 #- rbx-3

branches:
  only:
    - master

gemfile:
#  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4_0.gemfile
#  - gemfiles/rails_4_1.gemfile
#  - gemfiles/rails_4_2.gemfile
#  - gemfiles/rails_5_0.gemfile

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4_0.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4_1.gemfile 